# Generated by Django 6.0.1 on 2026-01-24 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_size", models.IntegerField()),
                ("equipment_count", models.IntegerField()),
                ("summary_data", models.JSONField()),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
